// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_widening_object_keys

import "github.com/go-json-experiment/json"

type NoWideningObjectKeysOptions struct {
	Keys    string `json:"keys,omitempty"`
	Entries string `json:"entries,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoWideningObjectKeysOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoWideningObjectKeysOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["keys"]; !ok || v == nil {
		plain.Keys = "typedKeys"
	}
	if v, ok := raw["entries"]; !ok || v == nil {
		plain.Entries = "typedEntries"
	}
	*j = NoWideningObjectKeysOptions(plain)
	return nil
}
