// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_widening_return_type

import "github.com/go-json-experiment/json"

type NoWideningReturnTypeOptions struct {
	Contracts bool `json:"contracts,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoWideningReturnTypeOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoWideningReturnTypeOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["contracts"]; !ok || v == nil {
		plain.Contracts = true
	}
	*j = NoWideningReturnTypeOptions(plain)
	return nil
}
